openapi: 3.2.0
info:
  description: API for KMD (Key Management Daemon)
  title: KMD HTTP Program API
  contact:
    email: contact@algorand.com
  version: 0.0.1
servers:
- url: http://localhost/
security:
- api_key: []
tags:
- name: Program
paths:
  /v1/program/sign:
    post:
      description: Signs the passed program with a key from the wallet, determined by the account named in the request.
      summary: Sign program
      operationId: SignProgram
      responses:
        '200':
          $ref: '#/components/responses/SignProgramResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignProgramRequest'
        required: true
      tags:
      - Program
components:
  schemas:
    APIV1POSTProgramSignResponse:
      description: 'APIV1POSTProgramSignResponse is the response to `POST /v1/data/sign`

        friendly:SignProgramResponse'
      type: object
      properties:
        error:
          type: boolean
          x-go-name: Error
        message:
          type: string
          x-go-name: Message
        sig:
          type: string
          format: byte
          x-go-name: Signature
      x-go-package: github.com/algorand/go-algorand/daemon/kmd/lib/kmdapi
    SignProgramRequest:
      description: APIV1POSTProgramSignRequest is the request for `POST /v1/program/sign`
      type: object
      properties:
        address:
          type: string
          x-go-name: Address
        data:
          type: string
          format: byte
          x-go-name: Program
        wallet_handle_token:
          type: string
          x-go-name: WalletHandleToken
        wallet_password:
          type: string
          x-go-name: WalletPassword
      x-go-name: APIV1POSTProgramSignRequest
      x-go-package: github.com/algorand/go-algorand/daemon/kmd/lib/kmdapi
  responses:
    SignProgramResponse:
      description: Response to `POST /v1/data/sign`
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIV1POSTProgramSignResponse'
  securitySchemes:
    api_key:
      description: 'Generated header parameter. This value can be found in `/kmd/data/dir/kmd.token`. Example value: ''330b2e4fc9b20f4f89812cf87f1dabeb716d23e3f11aec97a61ff5f750563b78'''
      type: apiKey
      name: X-KMD-API-Token
      in: header
      x-example: 330b2e4fc9b20f4f89812cf87f1dabeb716d23e3f11aec97a61ff5f750563b78
