openapi: 3.2.0
info:
  description: API for KMD (Key Management Daemon)
  title: KMD HTTP Wallets API
  contact:
    email: contact@algorand.com
  version: 0.0.1
servers:
- url: http://localhost/
security:
- api_key: []
tags:
- name: Wallets
paths:
  /v1/wallets:
    get:
      description: Lists all of the wallets that kmd is aware of.
      summary: List wallets
      operationId: ListWallets
      responses:
        '200':
          $ref: '#/components/responses/ListWalletsResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListWalletsRequest'
      tags:
      - Wallets
components:
  schemas:
    APIV1Wallet:
      description: APIV1Wallet is the API's representation of a wallet
      type: object
      properties:
        driver_name:
          type: string
          x-go-name: DriverName
        driver_version:
          type: integer
          format: uint32
          x-go-name: DriverVersion
        id:
          type: string
          x-go-name: ID
        mnemonic_ux:
          type: boolean
          x-go-name: SupportsMnemonicUX
        name:
          type: string
          x-go-name: Name
        supported_txs:
          type: array
          items:
            $ref: '#/components/schemas/TxType'
          x-go-name: SupportedTransactions
      x-go-package: github.com/algorand/go-algorand/daemon/kmd/lib/kmdapi
    ListWalletsRequest:
      description: APIV1GETWalletsRequest is the request for `GET /v1/wallets`
      type: object
      x-go-name: APIV1GETWalletsRequest
      x-go-package: github.com/algorand/go-algorand/daemon/kmd/lib/kmdapi
    APIV1GETWalletsResponse:
      description: 'APIV1GETWalletsResponse is the response to `GET /v1/wallets`

        friendly:ListWalletsResponse'
      type: object
      properties:
        error:
          type: boolean
          x-go-name: Error
        message:
          type: string
          x-go-name: Message
        wallets:
          type: array
          items:
            $ref: '#/components/schemas/APIV1Wallet'
          x-go-name: Wallets
      x-go-package: github.com/algorand/go-algorand/daemon/kmd/lib/kmdapi
    TxType:
      description: TxType is the type of the transaction written to the ledger
      type: string
      x-go-package: github.com/algorand/go-algorand/protocol
  responses:
    ListWalletsResponse:
      description: Response to `GET /v1/wallets`
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIV1GETWalletsResponse'
  securitySchemes:
    api_key:
      description: 'Generated header parameter. This value can be found in `/kmd/data/dir/kmd.token`. Example value: ''330b2e4fc9b20f4f89812cf87f1dabeb716d23e3f11aec97a61ff5f750563b78'''
      type: apiKey
      name: X-KMD-API-Token
      in: header
      x-example: 330b2e4fc9b20f4f89812cf87f1dabeb716d23e3f11aec97a61ff5f750563b78
