openapi: 3.2.0
info:
  description: API for KMD (Key Management Daemon)
  title: KMD HTTP Key API
  contact:
    email: contact@algorand.com
  version: 0.0.1
servers:
- url: http://localhost/
security:
- api_key: []
tags:
- name: Key
paths:
  /v1/key:
    post:
      description: Generates the next key in the deterministic key sequence (as determined by the master derivation key) and adds it to the wallet, returning the public key.
      summary: Generate a key
      operationId: GenerateKey
      responses:
        '200':
          $ref: '#/components/responses/GenerateKeyResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateKeyRequest'
        required: true
      tags:
      - Key
    delete:
      description: Deletes the key with the passed public key from the wallet.
      summary: Delete a key
      operationId: DeleteKey
      responses:
        '200':
          $ref: '#/components/responses/DeleteKeyResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteKeyRequest'
        required: true
      tags:
      - Key
  /v1/key/export:
    post:
      description: Export the secret key associated with the passed public key.
      summary: Export a key
      operationId: ExportKey
      responses:
        '200':
          $ref: '#/components/responses/ExportKeyResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExportKeyRequest'
        required: true
      tags:
      - Key
  /v1/key/import:
    post:
      description: Import an externally generated key into the wallet. Note that if you wish to back up the imported key, you must do so by backing up the entire wallet database, because imported keys were not derived from the wallet's master derivation key.
      summary: Import a key
      operationId: ImportKey
      responses:
        '200':
          $ref: '#/components/responses/ImportKeyResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImportKeyRequest'
        required: true
      tags:
      - Key
  /v1/key/list:
    post:
      description: Lists all of the public keys in this wallet. All of them have a stored private key.
      summary: List keys in wallet
      operationId: ListKeysInWallet
      responses:
        '200':
          $ref: '#/components/responses/ListKeysResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListKeysRequest'
        required: true
      tags:
      - Key
components:
  schemas:
    ed25519PrivateKey:
      type: array
      items:
        type: integer
        format: uint8
      x-go-package: github.com/algorand/go-algorand/crypto
    APIV1DELETEKeyResponse:
      description: 'APIV1DELETEKeyResponse is the response to `DELETE /v1/key`

        friendly:DeleteKeyResponse'
      type: object
      properties:
        error:
          type: boolean
          x-go-name: Error
        message:
          type: string
          x-go-name: Message
      x-go-package: github.com/algorand/go-algorand/daemon/kmd/lib/kmdapi
    APIV1POSTKeyImportResponse:
      description: 'APIV1POSTKeyImportResponse is the response to `POST /v1/key/import`

        friendly:ImportKeyResponse'
      type: object
      properties:
        address:
          type: string
          x-go-name: Address
        error:
          type: boolean
          x-go-name: Error
        message:
          type: string
          x-go-name: Message
      x-go-package: github.com/algorand/go-algorand/daemon/kmd/lib/kmdapi
    DeleteKeyRequest:
      description: APIV1DELETEKeyRequest is the request for `DELETE /v1/key`
      type: object
      properties:
        address:
          type: string
          x-go-name: Address
        wallet_handle_token:
          type: string
          x-go-name: WalletHandleToken
        wallet_password:
          type: string
          x-go-name: WalletPassword
      x-go-name: APIV1DELETEKeyRequest
      x-go-package: github.com/algorand/go-algorand/daemon/kmd/lib/kmdapi
    ImportKeyRequest:
      description: APIV1POSTKeyImportRequest is the request for `POST /v1/key/import`
      type: object
      properties:
        private_key:
          $ref: '#/components/schemas/PrivateKey'
        wallet_handle_token:
          type: string
          x-go-name: WalletHandleToken
      x-go-name: APIV1POSTKeyImportRequest
      x-go-package: github.com/algorand/go-algorand/daemon/kmd/lib/kmdapi
    ListKeysRequest:
      description: APIV1POSTKeyListRequest is the request for `POST /v1/key/list`
      type: object
      properties:
        wallet_handle_token:
          type: string
          x-go-name: WalletHandleToken
      x-go-name: APIV1POSTKeyListRequest
      x-go-package: github.com/algorand/go-algorand/daemon/kmd/lib/kmdapi
    PrivateKey:
      description: PrivateKey is an exported ed25519PrivateKey
      $ref: '#/components/schemas/ed25519PrivateKey'
    APIV1POSTKeyListResponse:
      description: 'APIV1POSTKeyListResponse is the response to `POST /v1/key/list`

        friendly:ListKeysResponse'
      type: object
      properties:
        addresses:
          type: array
          items:
            type: string
          x-go-name: Addresses
        error:
          type: boolean
          x-go-name: Error
        message:
          type: string
          x-go-name: Message
      x-go-package: github.com/algorand/go-algorand/daemon/kmd/lib/kmdapi
    GenerateKeyRequest:
      description: APIV1POSTKeyRequest is the request for `POST /v1/key`
      type: object
      properties:
        display_mnemonic:
          type: boolean
          x-go-name: DisplayMnemonic
        wallet_handle_token:
          type: string
          x-go-name: WalletHandleToken
      x-go-name: APIV1POSTKeyRequest
      x-go-package: github.com/algorand/go-algorand/daemon/kmd/lib/kmdapi
    APIV1POSTKeyExportResponse:
      description: 'APIV1POSTKeyExportResponse is the response to `POST /v1/key/export`

        friendly:ExportKeyResponse'
      type: object
      properties:
        error:
          type: boolean
          x-go-name: Error
        message:
          type: string
          x-go-name: Message
        private_key:
          $ref: '#/components/schemas/PrivateKey'
      x-go-package: github.com/algorand/go-algorand/daemon/kmd/lib/kmdapi
    ExportKeyRequest:
      description: APIV1POSTKeyExportRequest is the request for `POST /v1/key/export`
      type: object
      properties:
        address:
          type: string
          x-go-name: Address
        wallet_handle_token:
          type: string
          x-go-name: WalletHandleToken
        wallet_password:
          type: string
          x-go-name: WalletPassword
      x-go-name: APIV1POSTKeyExportRequest
      x-go-package: github.com/algorand/go-algorand/daemon/kmd/lib/kmdapi
    APIV1POSTKeyResponse:
      description: 'APIV1POSTKeyResponse is the response to `POST /v1/key`

        friendly:GenerateKeyResponse'
      type: object
      properties:
        address:
          type: string
          x-go-name: Address
        error:
          type: boolean
          x-go-name: Error
        message:
          type: string
          x-go-name: Message
      x-go-package: github.com/algorand/go-algorand/daemon/kmd/lib/kmdapi
  responses:
    ExportKeyResponse:
      description: Response to `POST /v1/key/export`
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIV1POSTKeyExportResponse'
    ImportKeyResponse:
      description: Response to `POST /v1/key/import`
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIV1POSTKeyImportResponse'
    DeleteKeyResponse:
      description: Response to `DELETE /v1/key`
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIV1DELETEKeyResponse'
    GenerateKeyResponse:
      description: Response to `POST /v1/key`
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIV1POSTKeyResponse'
    ListKeysResponse:
      description: Response to `POST /v1/key/list`
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIV1POSTKeyListResponse'
  securitySchemes:
    api_key:
      description: 'Generated header parameter. This value can be found in `/kmd/data/dir/kmd.token`. Example value: ''330b2e4fc9b20f4f89812cf87f1dabeb716d23e3f11aec97a61ff5f750563b78'''
      type: apiKey
      name: X-KMD-API-Token
      in: header
      x-example: 330b2e4fc9b20f4f89812cf87f1dabeb716d23e3f11aec97a61ff5f750563b78
