openapi: 3.2.0
info:
  contact:
    name: Algorand
    url: https://www.algorand.com/get-in-touch/contact
  description: Algorand ledger analytics API.
  title: Indexer Common API
  version: '2.0'
servers:
- url: https://example.com/
tags:
- name: Common
paths:
  /health:
    get:
      operationId: makeHealthCheck
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
          description: (empty)
        default:
          content: {}
          description: Unknown Error
      summary: Returns 200 if healthy
      tags:
      - Common
components:
  schemas:
    HealthCheck:
      description: A health check response.
      properties:
        data:
          properties: {}
          type: object
        db-available:
          type: boolean
        errors:
          items:
            type: string
          type: array
        is-migrating:
          type: boolean
        message:
          type: string
        round:
          type: integer
        version:
          description: Current version.
          type: string
      required:
      - db-available
      - is-migrating
      - message
      - round
      - version
      type: object
x-original-swagger-version: '2.0'
